### ISSUE TITLE
Protagonist install fails with dredd and alone on Ubuntu 16.04 docker image

### ISSUE THREAD

**Issue by mhueter** [apiaryio/protagonist#156]
Hello,

Having some problems installing dredd on a Ubuntu docker image, but the problem seems to be due to protagonist as I get the same error when I try to install protagonist by itself first.

**Docker image information:**

_base image:_ ubuntu:16.04
_installed:_ `build-essential`, `libkrb5-dev`, `software-properties-common`, `python python-dev python-pip python-virtualenv`, `nodejs`.

**[Download the image here](https://hub.docker.com/r/mhueter/node-python-ruby/)**

`npm install protagonist` results:

```
> protagonist@1.3.3 install /node_modules/protagonist
> node-gyp rebuild

module.js:442
    throw err;
    ^
Error: Cannot find module 'nan'
    at Function.Module._resolveFilename (module.js:440:15)
    at Function.Module._load (module.js:388:25)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at [eval]:1:1
    at Object.exports.runInThisContext (vm.js:54:17)
    at Object.<anonymous> ([eval]-wrapper:6:22)
    at Module._compile (module.js:541:32)
    at node.js:311:29
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
gyp: Call to 'node -e "require('nan')"' returned exit status 1 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:305:16)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)
gyp ERR! System Linux 4.4.12-boot2docker
gyp ERR! command "/usr/bin/nodejs" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /node_modules/protagonist
gyp ERR! node -v v6.2.2
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok
npm ERR! Linux 4.4.12-boot2docker
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "protagonist"
npm ERR! node v6.2.2
npm ERR! npm  v3.9.5
npm ERR! code ELIFECYCLE

npm ERR! protagonist@1.3.3 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the protagonist@1.3.3 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the protagonist package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs protagonist
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls protagonist
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /npm-debug.log
```

The error is the same when I run `npm install dredd`.

All I want to do is be able to run that command on the attached image without the dependency fail.

**Comment by mhueter** [comment]
also it works when I globally install it with `-g` but I need it to work from the `package.json` so I can `require` it in a Node script.

**Comment by kylef** [comment]
Looks like there's some problem where the nan dependency isn't installed / available.

```
Error: Cannot find module 'nan'
```

Does the following succeed?

```shell
$ npm install nan
```

**Comment by mhueter** [comment]
Yes, nan installs without issue (as does node-gyp).

**Comment by mhueter** [comment]
This issue is due to protagonist not working on Node 6.2.2. I switched to Node 4 and it installs properly.

**Comment by mhueter** [comment]
I got this working with a different base image with Node v4.4 - my initial post has Node v6.2.2, which probably isn't supported yet.

**Comment by w-vi** [comment]
Protagonist is tested on Node v6.1.x that's the latest node version available on travis so maybe 6.2.x has some issues.

**Comment by mhueter** [comment]
Same exact error output using an alpine linux Node 6 [docker image](https://hub.docker.com/r/mhart/alpine-node/). I couldn't find a 6.1.x image. So I switched to alpine linux Node 4.4.6 and it's working. 

This workaround isn't a problem for me (the only inconvenience is transposing ES6 down for Node 4).

**Comment by pksunkara** [comment]
Is it failing with OS X node 6.2.x too?

**Comment by mhueter** [comment]
@pksunkara OS X is working.

**Comment by w-vi** [comment]
Closing this one as it seems to be working, feel free to reopen if needed.
